In [16]:
import numpy as np

In [17]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a, a[1], a[1, 1], sep = ";\n")

[[1 2 3]
 [4 5 6]];
[4 5 6];
5


typing

In [18]:
from numpy.typing import NDArray

def func(a : NDArray) -> NDArray : return a

This section covers `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`

In [19]:
a = np.zeros(2)
b = np.ones((2, 2))
c = np.eye(3)
d = np.arange(4)
e = np.arange(8, 2, -2)
print(a, b, c, d, e, sep = ";\n")

[0. 0.];
[[1. 1.]
 [1. 1.]];
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]];
[0 1 2 3];
[8 6 4]


In [20]:
a = np.linspace(0, 1, 4)
b = np.linspace(0, 1, num = 4, endpoint=False)
c, step = np.linspace(0, 1, num = 4, retstep=True)
print(a, b, sep = ";")
print(c, step)

[0.         0.33333333 0.66666667 1.        ];[0.   0.25 0.5  0.75]
[0.         0.33333333 0.66666667 1.        ] 0.3333333333333333


This section covers the `ndim`, `shape`, `size`, and `dtype` attributes of an array.

In [21]:
print(a.ndim, a.shape, a.size, a.dtype, sep = ";")

1;(4,);4;float64


In [22]:
a = np.reshape(np.arange(24), (2, 3, 4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Slice : `arr[start:stop:step]`

In [23]:
a = np.reshape(np.arange(24), (3, 8))
print(a[:, 0:6:2])

[[ 0  2  4]
 [ 8 10 12]
 [16 18 20]]


Boolean Indexing

In [24]:
num = np.reshape(np.arange(12), (3, 4))
mask = (num>=5) | (num%2==0)
print(mask)
res = num[mask]
print(res)

[[ True False  True False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 0  2  4  5  6  7  8  9 10 11]


In [25]:
num = np.reshape(np.arange(12), (3, 4))
print(num[(num>=5) | (num%2==0)])

[ 0  2  4  5  6  7  8  9 10 11]


随机数

In [26]:
num = np.random.randn(5)             # 正态分布
print(num)
num = np.random.uniform(2, 3, 5)     # 生成5个(2,3)中均匀分布的随机浮点数
print(num)

[-0.69964463 -0.91651341  0.45994006 -1.09336759 -1.88168875]
[2.28542511 2.55787321 2.87475764 2.78329068 2.74562853]


In [27]:
num = np.random.randint(0, 10)        # 生成一个[0,10)之间的随机整数
print(num)

9


In [28]:
num = np.random.randint(0, 100, 5)    # 生成5个随机整数
print(num)

[66 61 86 24  8]


In [29]:
a = np.random.rand(2, 3)              # 生成2*3随机矩阵
print(a)

[[0.86715828 0.13859077 0.60461994]
 [0.77970897 0.19106991 0.50966574]]
