In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[1, 2],
              [3, 4]])
print(a + b, a - b, a * b, a / b, sep = "\n")
print(a * 1.5)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[1. 1.]
 [1. 1.]]
[[1.5 3. ]
 [4.5 6. ]]


# Broadcasting

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when
1. they are equal, or
2. one of them is 1.
If these conditions are not met, a `ValueError` is thrown.

Example :
```
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```

In [3]:
a = np.array([[1], [2], [3]]) # shape : (3, 1)
b = np.array([1, 2, 3]) # shape : (3,)
print(a - b) # shape : (3, 3)

[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]


multiple

In [4]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[1, 2],
              [3, 4]])
print(a @ b)

[[ 7 10]
 [15 22]]


# Einstein summation

Each letter represents a dimension label.

In [16]:
M = np.array([[1, 2],
              [3, 4]])

print(np.einsum('ij->ji', M))
print(M.T)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.einsum('i,j->ij', a, b))
print(np.outer(a, b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


If the part after `->` is empty, it indicates that the result is a scalar.

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.einsum('i,i->', a, b))
print(np.dot(a, b))

32
32


In [14]:
M = np.array([[1, 2],
              [3, 4]])

print(np.einsum('ii->', M))
print(np.trace(M))

5
5


In [31]:
M = np.array([[1, 2],
              [3, 4]])

print(np.einsum('ii->i', M))

[1 4]


Letters that appear in the inputs but not in the output are eliminated (summed out).

In [24]:
M = np.array([[1, 2],
              [3, 4]])
N = np.array([[5, 6],
              [7, 8]])

print(np.einsum('ik,kj->ij', M, N))
print(np.dot(M, N))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [44]:
M = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])

print(np.einsum('ijk->jk', M))
print(np.sum(M, axis=0))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [29]:
A = np.random.rand(10, 3, 4)  # 10 3x4 matrices
B = np.random.rand(10, 4, 5)  # 10 4x5 matrices
C = np.einsum('ijk,ikl->ijl', A, B)
print(C.shape)

(10, 3, 5)


Example

$$
\begin{cases}
x + y + z = 6 \\
x + 3 y - 2 z = 1 \\
2x - y + z = 3
\end{cases}
$$

In [5]:
A = np.array([[1, 1, 1],
              [1, 3, -2],
              [2, -1, 1]])
b = np.array([6, 1, 3])
print(np.linalg.solve(A, b)) # solution is [1 2 3]

[1. 2. 3.]


In [6]:
def forward_sub(L, b):
    n = L.shape[0]
    x, b = np.zeros(n), b.copy()
    for k in range(n):
        x[k] = b[k] / L[k, k]
        b[k:] -= L[k:, k] * x[k]
    return x

eigenvalue

In [7]:
A = np.array([[2, 2, -2],
              [2, 5, -4],
              [-2, -4, 5]])

eig_val, eig_vec = np.linalg.eig(A) # (-4, 1, -1)^T , (1, 2, -2)^T , (2, 4, 5)^T
print(eig_val, eig_vec)

[ 1. 10.  1.] [[-0.94280904  0.33333333  0.2981424 ]
 [ 0.23570226  0.66666667  0.59628479]
 [-0.23570226 -0.66666667  0.74535599]]


In [8]:
A = np.array([1, 2j])

print(np.max(np.abs(A)))

2.0


测试